# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-AxKit-Provider-File-Syntax
version:      0.03
version_from: Syntax.pm
installdirs:  site
requires:
    AxKit:                         1.6
    File::MimeInfo::Magic:         0.9
    Text::VimColor:                0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
